### ISSUE TITLE
Nano:  button works, but noise on rotary

### ISSUE THREAD

**Issue by brianssparetime** [John-Lluch/Encoder#4]
Thanks for the great library (no problems compiling on the nano btw!)

Unfortunately, I'm having trouble getting it to work right on my project.  The button functionality works no problem, but the rotary delta seems to be mostly 0s with a few 1, -1, 256, -255, etc that doesn't react to my turning the wheel.

I've tried now two separate arduinos (a nano and a mega) and two separate REs and wirings (one in my project, and a second isolated with only the RE in play and nothing else connected).

Even running stripped down code based on your model code, I can't seem to get it to work:  https://github.com/brianssparetime/darkroom_timer/blob/main/rotary_encoder_test/rotary_encoder_test.ino

In terms of hardware, I have one of the button pins and the middle pin of the RE tied to ground, and the remaining pins going directly to the digital inputs, as shown at the top of the code above.

I'm at a loss for what I'm doing wrong.  Any help would be appreciated.

**Comment by John-Lluch** [comment]
Thank you for your feedback. First of all, please note that I have only tested it on a pro-micro (ATMega32U4), so I can't be 100% sure that it works on a Nano. 

However, by looking at your code it seems to me that you have some misunderstanding of the way the library works. The 'delta' function just gives the encoder _variation_ since the last call to it, hence its name, not the actual encoder value. To get the accumulated value try to declare a global `int encoderValue` variable then put the following on the main loop:
```
int delta = encoder.delta();
encoderValue = encoderValue + delta; 
```
This way, you should get the actual encoder value in the `encoderValue` variable
Hope this helps

**Comment by brianssparetime** [comment]
Thank you for the thoughtful response. 

I understand that the delta represents the variation since the last call not an absolute value.   I'm using the very-poorly-named variable foo to accumulate the changes [here](https://github.com/brianssparetime/darkroom_timer/blob/dca49d2eb7fc499d6a5491b0578c744ae817346b/rotary_encoder_test/rotary_encoder_test.ino#L72-L78).   The delta is subtracted from foo, and then result is checked to keep it within bounds of 0-256, and then that result is saved back to foo for the next iteration.

The problem is that the delta returns a lot of small  (and sometimes very large) non-zero values even when the encoder isn't being touched, so I'm filtering out any movements with abs value <=1 or >= 255.  If I don't do this, my accumulated value very quickly goes to zero or 255 and gets stuck there.

Do you have caps/resistors involved in your hardware to reduce this noise?   Am I correct in supplying ground to the middle pin of the RE, or should I be giving it 5v?

**Comment by John-Lluch** [comment]
Hi Brian,
I do not have any hardware to reduce noise. Just the encoder directly wired to inputs. Please can you try with an even simpler code, like just the code I posted above. (However as said, this is not tested with ATmega328, so maybe there's something wrong in the library itself)

**Comment by John-Lluch** [comment]
Another thought. The library assumes pullup resistors are physically placed on the A, B encoder inputs. The KY-040 Encoder Module have them, so you do not need to do anything else. However if you are using an encoder component (not the encoder module) then you either have to physically wire the resistors, or to set the inputs as "INPUT_PULLUP", look at the Encoder::init() funcion

**Comment by brianssparetime** [comment]
I was not using the KY040 module, just a bare encoder.  Adding the pullup resistors indeed fixed the problem perfectly.  I just added 10ks from A and B to +5v as you suggested, and now everything works exactly as expected.

Thank you again.  This library is a dream to use!

**Comment by John-Lluch** [comment]
Ok, Thanks again for your feedback
